set_property SRC_FILE_INFO {cfile:C:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/constrs_1/new/Top.xdc rfile:../../../axi_10g_ethernet_0_ex.srcs/constrs_1/new/Top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T26 [get_ports CLK_OnBoard_p]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T27 [get_ports CLK_OnBoard_n]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports ROD_TDO]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports ROD_TDI]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K11 [get_ports ROD_TMS]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L11 [get_ports ROD_TCK]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J29 [get_ports FEB_TDO]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H29 [get_ports FEB_TDI]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J27 [get_ports FEB_TMS]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J28 [get_ports FEB_TCK]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K28 [get_ports FEB1_clk_p]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K29 [get_ports FEB1_clk_n]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L26 [get_ports ROD_CMD_FEB1_p]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L27 [get_ports ROD_CMD_FEB1_n]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M24 [get_ports FEB1_Response_p]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M25 [get_ports FEB1_Response_n]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M29 [get_ports Trigger_FEB1_p]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M30 [get_ports Trigger_FEB1_n]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L25 [get_ports FEB2_clk_p]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K25 [get_ports FEB2_clk_n]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N21 [get_ports ROD_CMD_FEB2_p]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports ROD_CMD_FEB2_n]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports FEB2_Response_p]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports FEB2_Response_n]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports Trigger_FEB2_p]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M23 [get_ports Trigger_FEB2_n]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports FEB3_clk_p]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports FEB3_clk_n]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports ROD_CMD_FEB3_p]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports ROD_CMD_FEB3_n]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports FEB3_Response_p]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports FEB3_Response_n]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports Trigger_FEB3_p]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports Trigger_FEB3_n]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports FEB4_clk_p]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports FEB4_clk_n]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports ROD_CMD_FEB4_p]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports ROD_CMD_FEB4_n]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports FEB4_Response_p]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports FEB4_Response_n]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports Trigger_FEB4_p]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports Trigger_FEB4_n]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12 [get_ports FEB5_clk_p]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports FEB5_clk_n]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports ROD_CMD_FEB5_p]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J12 [get_ports ROD_CMD_FEB5_n]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports FEB5_Response_p]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports FEB5_Response_n]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports Trigger_FEB5_p]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports Trigger_FEB5_n]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports FEB6_clk_p]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports FEB6_clk_n]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports ROD_CMD_FEB6_p]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports ROD_CMD_FEB6_n]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports FEB6_Response_p]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports FEB6_Response_n]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports Trigger_FEB6_p]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports Trigger_FEB6_n]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB27 [get_ports External_Trigger]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports Q2_CLK0_GTREFCLK_PAD_P_IN]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports Q2_CLK0_GTREFCLK_PAD_N_IN]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells GTX_ROD_Datalink_inst/GTX_ROD_Link_support_i/GTX_ROD_Link_init_i/inst/GTX_ROD_Link_i/gt0_GTX_ROD_Link_i/gtxe2_i]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {RXN_IN[0]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {RXP_IN[0]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {TXN_OUT[0]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {TXP_OUT[0]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells GTX_ROD_Datalink_inst/GTX_ROD_Link_support_i/GTX_ROD_Link_init_i/inst/GTX_ROD_Link_i/gt1_GTX_ROD_Link_i/gtxe2_i]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {RXN_IN[1]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports {RXP_IN[1]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {TXN_OUT[1]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {TXP_OUT[1]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y8 [get_cells GTX_ROD_Datalink_inst/GTX_ROD_Link_support_i/GTX_ROD_Link_init_i/inst/GTX_ROD_Link_i/gt2_GTX_ROD_Link_i/gtxe2_i]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {RXN_IN[2]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {RXP_IN[2]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {TXN_OUT[2]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports {TXP_OUT[2]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y9 [get_cells GTX_ROD_Datalink_inst/GTX_ROD_Link_support_i/GTX_ROD_Link_init_i/inst/GTX_ROD_Link_i/gt3_GTX_ROD_Link_i/gtxe2_i]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports {RXN_IN[3]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports {RXP_IN[3]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports {TXN_OUT[3]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {TXP_OUT[3]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y12 [get_cells GTX_ROD_Datalink_inst/GTX_ROD_Link_support_i/GTX_ROD_Link_init_i/inst/GTX_ROD_Link_i/gt4_GTX_ROD_Link_i/gtxe2_i]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {RXN_IN[4]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E4 [get_ports {RXP_IN[4]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {TXN_OUT[4]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports {TXP_OUT[4]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y13 [get_cells GTX_ROD_Datalink_inst/GTX_ROD_Link_support_i/GTX_ROD_Link_init_i/inst/GTX_ROD_Link_i/gt5_GTX_ROD_Link_i/gtxe2_i]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {RXN_IN[5]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {RXP_IN[5]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {TXN_OUT[5]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {TXP_OUT[5]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports ethernet_refclk_in_p]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports ethernet_refclk_in_n]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3 [get_ports SFP_rx_n]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports SFP_rx_p]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1 [get_ports SFP_tx_n]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2 [get_ports SFP_tx_p]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ27 [get_ports SFP_tx0_disable]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH27 [get_ports SFP_tx1_disable]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list Ethernet_10G_inst/fifo_block_i/ethernet_core_i/inst/xpcs/inst/ten_gig_eth_pcs_pma_shared_clock_reset_block/coreclk_out]]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {Ethernet_10G_inst/arp_block/arp_parse/op_code[0]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[1]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[2]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[3]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[4]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[5]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[6]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[7]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[8]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[9]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[10]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[11]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[12]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[13]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[14]} {Ethernet_10G_inst/arp_block/arp_parse/op_code[15]}]]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {Ethernet_10G_inst/arp_block/arp_parse/src_mac[0]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[1]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[2]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[3]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[4]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[5]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[6]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[7]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[8]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[9]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[10]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[11]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[12]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[13]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[14]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[15]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[16]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[17]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[18]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[19]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[20]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[21]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[22]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[23]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[24]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[25]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[26]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[27]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[28]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[29]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[30]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[31]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[32]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[33]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[34]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[35]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[36]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[37]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[38]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[39]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[40]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[41]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[42]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[43]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[44]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[45]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[46]} {Ethernet_10G_inst/arp_block/arp_parse/src_mac[47]}]]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {Ethernet_10G_inst/arp_block/arp_parse/des_mac[0]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[1]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[2]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[3]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[4]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[5]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[6]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[7]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[8]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[9]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[10]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[11]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[12]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[13]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[14]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[15]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[16]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[17]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[18]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[19]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[20]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[21]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[22]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[23]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[24]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[25]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[26]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[27]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[28]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[29]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[30]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[31]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[32]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[33]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[34]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[35]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[36]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[37]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[38]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[39]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[40]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[41]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[42]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[43]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[44]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[45]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[46]} {Ethernet_10G_inst/arp_block/arp_parse/des_mac[47]}]]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {Ethernet_10G_inst/arp_block/arp_parse/des_ip[0]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[1]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[2]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[3]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[4]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[5]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[6]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[7]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[8]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[9]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[10]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[11]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[12]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[13]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[14]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[15]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[16]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[17]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[18]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[19]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[20]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[21]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[22]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[23]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[24]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[25]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[26]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[27]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[28]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[29]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[30]} {Ethernet_10G_inst/arp_block/arp_parse/des_ip[31]}]]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {Ethernet_10G_inst/arp_block/arp_parse/rx_type[0]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[1]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[2]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[3]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[4]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[5]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[6]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[7]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[8]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[9]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[10]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[11]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[12]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[13]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[14]} {Ethernet_10G_inst/arp_block/arp_parse/rx_type[15]}]]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {Ethernet_10G_inst/arp_block/arp_parse/src_ip[0]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[1]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[2]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[3]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[4]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[5]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[6]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[7]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[8]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[9]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[10]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[11]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[12]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[13]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[14]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[15]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[16]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[17]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[18]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[19]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[20]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[21]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[22]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[23]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[24]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[25]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[26]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[27]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[28]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[29]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[30]} {Ethernet_10G_inst/arp_block/arp_parse/src_ip[31]}]]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list Ethernet_10G_inst/tcp_en]]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_coreclk_out]
