# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_GTX_Decode.xci
# IP: The module: 'ila_GTX_Decode' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_GTX_Decode'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_GTX_Decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_GTX_Decode_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_GTX_Decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_GTX_Decode.xci
# IP: The module: 'ila_GTX_Decode' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_GTX_Decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_GTX_Decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/ila_GTX_Decode/ila_GTX_Decode_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_GTX_Decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
