# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
# IP: The module: 'axi_10g_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb || ORIG_REF_NAME==bd_efdb} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/bd_efdb_xmac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_xmac_0 || ORIG_REF_NAME==bd_efdb_xmac_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/bd_efdb_xpcs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_xpcs_0 || ORIG_REF_NAME==bd_efdb_xpcs_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/bd_efdb_prtad_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_prtad_driver_0 || ORIG_REF_NAME==bd_efdb_prtad_driver_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/bd_efdb_dcm_locked_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_dcm_locked_driver_0 || ORIG_REF_NAME==bd_efdb_dcm_locked_driver_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_4/bd_efdb_pma_pmd_type_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_efdb_pma_pmd_type_driver_0} -quiet] -quiet

# XDC: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_ooc.xdc

# XDC: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_10g_ethernet_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
# IP: The module: 'axi_10g_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb || ORIG_REF_NAME==bd_efdb} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/bd_efdb_xmac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_xmac_0 || ORIG_REF_NAME==bd_efdb_xmac_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/bd_efdb_xpcs_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_xpcs_0 || ORIG_REF_NAME==bd_efdb_xpcs_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/bd_efdb_prtad_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_prtad_driver_0 || ORIG_REF_NAME==bd_efdb_prtad_driver_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/bd_efdb_dcm_locked_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_dcm_locked_driver_0 || ORIG_REF_NAME==bd_efdb_dcm_locked_driver_0} -quiet] -quiet

# IP: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_4/bd_efdb_pma_pmd_type_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_efdb_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_efdb_pma_pmd_type_driver_0} -quiet] -quiet

# XDC: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/bd_efdb_ooc.xdc

# XDC: c:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/axi_10g_ethernet_0_ex.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_10g_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
