# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/123/Documents/xilinx_project/SiTCP/axi_10g_ethernet_0_ex/imports/axi_10g_ethernet_0_example_design.xdc

# XDC: new/Top.xdc

# IP: C:/Users/123/Documents/xilinx_project/STAR/STAR.srcs/sources_1/ip/GTX_ROD_Link/GTX_ROD_Link.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GTX_ROD_Link || ORIG_REF_NAME==GTX_ROD_Link} -quiet] -quiet
