@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jan 13 21:13:30 +0800 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 2e6bea84743140ee8b6f6461b6dbf8f8 --debug typical --relax --mt 2 -L ten_gig_eth_mac_v15_1_7 -L xil_defaultlib -L gtwizard_ultrascale_v1_7_7 -L ten_gig_eth_pcs_pma_v6_0_16 -L xlconstant_v1_1_6 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot axi_10g_ethernet_0_demo_tb_behav xil_defaultlib.axi_10g_ethernet_0_demo_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 2e6bea84743140ee8b6f6461b6dbf8f8 --debug typical --relax --mt 2 -L ten_gig_eth_mac_v15_1_7 -L xil_defaultlib -L gtwizard_ultrascale_v1_7_7 -L ten_gig_eth_pcs_pma_v6_0_16 -L xlconstant_v1_1_6 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot axi_10g_ethernet_0_demo_tb_behav xil_defaultlib.axi_10g_ethernet_0_demo_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
